name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # Ana branch'e her itme olayında çalışacak

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          APP_NAME=mywebapp
          VERSION=latest
          docker build -t $APP_NAME:$VERSION .

      - name: Run Docker Container
        run: |
          APP_NAME=mywebapp
          VERSION=latest
          docker run -d -p 80:80 --name $APP_NAME $APP_NAME:$VERSION